#!/bin/bash
set -e

cat << EOF > /tmp/init.sql
CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE}\`;
GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
FLUSH PRIVILEGES;
EOF

mariadb -u ${MARIADB_ROOT_USER} -p${MARIADB_ROOT_PASSWORD} < /tmp/init.sql

rm /tmp/init.sql